from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Protocol

from backend.domain.models import (
    ApiTokenRecord,
    ArtifactRecord,
    JobRecord,
    ReviewRecord,
    RunRecord,
    SecretRecord,
    UserRecord,
    WorkerRecord,
    WorkflowTemplate,
    WorkspaceDefinition,
)


class WorkspaceRepositoryProtocol(Protocol):
    def list_workflow_templates(self) -> list[WorkflowTemplate]: ...
    def get_workflow_template(self, template_id: str) -> WorkflowTemplate: ...
    def upsert_workflow_template(self, template: WorkflowTemplate) -> None: ...
    def delete_workflow_template(self, template_id: str) -> None: ...
    def list_workspaces(self) -> list[WorkspaceDefinition]: ...
    def get_workspace(self, workspace_id: str) -> WorkspaceDefinition: ...
    def upsert_workspace(self, workspace: WorkspaceDefinition) -> None: ...
    def delete_workspace(self, workspace_id: str) -> None: ...


class RunRepositoryProtocol(Protocol):
    def save(self, run: RunRecord) -> None: ...
    def save_recovery_transition_if_stale(
        self,
        run: RunRecord,
        *,
        expected_status: str,
        expected_updated_at: str,
        active_lease_after: str,
    ) -> bool: ...
    def get(self, run_id: str) -> RunRecord: ...
    def list_runs(self, *, limit: int = 50, offset: int = 0, status: str = "", workspace_id: str = "") -> list[RunRecord]: ...
    def claim_next_queued(self) -> RunRecord | None: ...
    def delete(self, run_id: str) -> None: ...


class JobStoreProtocol(Protocol):
    def save_job_set(self, run_id: str, set_key: str, jobs: list[JobRecord]) -> None: ...
    def load_job_set(self, run_id: str, set_key: str) -> list[JobRecord]: ...
    def list_job_set_keys(self, run_id: str) -> list[str]: ...
    def load_all_job_sets(self, run_id: str) -> dict[str, list[JobRecord]]: ...
    def load_job_sets_for_runs(self, run_ids: Iterable[str]) -> dict[str, dict[str, list[JobRecord]]]: ...
    def delete_job_set(self, run_id: str, set_key: str) -> None: ...
    def save_blob(self, run_id: str, blob_key: str, payload: Any) -> None: ...
    def load_blob(self, run_id: str, blob_key: str, default: Any = None) -> Any: ...
    def list_blob_keys(self, run_id: str) -> list[str]: ...
    def load_all_blobs(self, run_id: str) -> dict[str, Any]: ...
    def delete_blob(self, run_id: str, blob_key: str) -> None: ...
    def clear_run(self, run_id: str) -> None: ...


class ArtifactStoreProtocol(Protocol):
    def save_artifacts(self, run_id: str, artifacts: list[ArtifactRecord]) -> None: ...
    def load_artifacts(self, run_id: str) -> list[ArtifactRecord]: ...
    def load_artifacts_for_runs(self, run_ids: Iterable[str]) -> dict[str, list[ArtifactRecord]]: ...
    def get_artifact(self, run_id: str, artifact_id: str) -> ArtifactRecord: ...
    def upsert_artifact(self, run_id: str, artifact: ArtifactRecord) -> None: ...
    def delete_artifact(self, run_id: str, artifact_id: str) -> None: ...
    def clear_run(self, run_id: str) -> None: ...


class ReviewStoreProtocol(Protocol):
    def upsert_review(self, review: ReviewRecord) -> None: ...
    def get_review(self, review_id: str) -> ReviewRecord: ...
    def list_reviews(self, *, run_id: str = "", limit: int = 100, offset: int = 0, status: str = "") -> list[ReviewRecord]: ...
    def list_reviews_for_runs(self, run_ids: Iterable[str]) -> dict[str, list[ReviewRecord]]: ...
    def append_application_status_history(self, entry: Mapping[str, Any]) -> None: ...
    def list_application_status_history(self, *, user_id: str = "", review_id: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def delete_review(self, review_id: str) -> None: ...


class AuthRepositoryProtocol(Protocol):
    def list_users(self) -> list[UserRecord]: ...
    def get_user(self, user_id: str) -> UserRecord: ...
    def get_user_by_email(self, email: str) -> UserRecord: ...
    def upsert_user(self, user: UserRecord) -> None: ...
    def delete_user(self, user_id: str) -> None: ...
    def list_api_tokens(self, *, user_id: str = "", active_only: bool = False) -> list[ApiTokenRecord]: ...
    def list_api_tokens_for_value(self, token_value: str, *, active_only: bool = False) -> list[ApiTokenRecord]: ...
    def get_api_token(self, token_id: str) -> ApiTokenRecord: ...
    def upsert_api_token(self, token: ApiTokenRecord) -> None: ...
    def delete_api_token(self, token_id: str) -> None: ...


class SecretStoreProtocol(Protocol):
    def list_secrets(self, *, workspace_id: str = "", limit: int = 100, offset: int = 0) -> list[SecretRecord]: ...
    def get_secret(self, secret_id: str) -> SecretRecord: ...
    def upsert_secret(self, secret: SecretRecord) -> None: ...
    def delete_secret(self, secret_id: str) -> None: ...


class WorkerStoreProtocol(Protocol):
    def list_workers(self, *, limit: int = 50, offset: int = 0, status: str = "") -> list[WorkerRecord]: ...
    def list_expired_workers(self, *, expires_before: str) -> list[WorkerRecord]: ...
    def get_worker(self, worker_id: str) -> WorkerRecord: ...
    def upsert_worker(self, worker: WorkerRecord) -> None: ...
    def renew_worker_lease_if_owned(
        self,
        observed: WorkerRecord,
        renewed: WorkerRecord,
        *,
        run_attempt_count: int,
    ) -> bool: ...
    def mark_stale_if_expired(
        self,
        worker: WorkerRecord,
        *,
        expires_before: str,
        stale_at: str,
    ) -> bool: ...
    def delete_worker(self, worker_id: str) -> None: ...


class AnalyticsStoreProtocol(Protocol):
    def emit_event(self, event: Mapping[str, Any]) -> None: ...
    def query_rows(self, query: str, parameters: Iterable[Any] = ()) -> list[dict[str, Any]]: ...
    def list_events(self, *, event_name: str = "", user_id: str = "", workspace_id: str = "", run_id: str = "", limit: int = 100, offset: int = 0) -> list[dict[str, Any]]: ...
    def count_events(self, *, event_name: str = "", user_id: str = "", workspace_id: str = "", run_id: str = "") -> int: ...


class ConfigStoreProtocol(Protocol):
    def get_value(self, config_key: str, default: Any = None) -> Any: ...
    def set_value(self, config_key: str, value: Any) -> None: ...
    def delete_value(self, config_key: str) -> None: ...
    def list_values(self, *, prefix: str = "") -> dict[str, Any]: ...


class SourcePolicyStoreProtocol(Protocol):
    def ensure_sites(self, sites: Iterable[Mapping[str, Any]]) -> None: ...
    def set_site_state(self, site_url: str, state: Mapping[str, Any]) -> None: ...
    def mark_workspace_selected(self, *, workspace_id: str, site_urls: Iterable[str]) -> None: ...
    def filter_crawlable_sites(self, sites: Iterable[Mapping[str, Any]], *, workspace_id: str = "") -> list[dict[str, Any]]: ...
    def record_site_yield(self, site_url: str, *, workspace_id: str = "", job_count: int = 0) -> None: ...
    def get_site_policy(self, site_url: str) -> dict[str, Any]: ...
    def get_seen_job_urls(self, *, workspace_id: str = "", source_id: str = "") -> set[str]: ...
    def get_cached_job_postings(self, *, workspace_id: str = "", source_id: str = "") -> list[dict[str, Any]]: ...
    def record_job_url_attempts(self, attempts: Iterable[Mapping[str, Any]]) -> None: ...


@dataclass(slots=True)
class BackendRepositories:
    workspace_repository: WorkspaceRepositoryProtocol
    run_repository: RunRepositoryProtocol
    job_store: JobStoreProtocol
    artifact_store: ArtifactStoreProtocol
    review_store: ReviewStoreProtocol
    auth_repository: AuthRepositoryProtocol
    secret_store: SecretStoreProtocol
    worker_store: WorkerStoreProtocol
    analytics_store: AnalyticsStoreProtocol
    config_store: ConfigStoreProtocol
    source_policy_store: SourcePolicyStoreProtocol | None = None
