from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Protocol

from backend.domain.assisted_apply import AssistedApplyConnectionRecord, AssistedApplyPreferences
from backend.domain.evidence import EvidenceRecord, EvidenceStateHistory

from backend.domain.models import (
    CareerProfile,

    ApiTokenRecord,
    ArtifactRecord,
    JobRecord,
    ReviewRecord,
    RunRecord,
    SecretRecord,
    UserRecord,
    WorkerRecord,
    WorkflowTemplate,
    WorkspaceDefinition,
)


class WorkspaceRepositoryProtocol(Protocol):
    def list_workflow_templates(self) -> list[WorkflowTemplate]: ...
    def get_workflow_template(self, template_id: str) -> WorkflowTemplate: ...
    def upsert_workflow_template(self, template: WorkflowTemplate) -> None: ...
    def delete_workflow_template(self, template_id: str) -> None: ...
    def list_workspaces(self) -> list[WorkspaceDefinition]: ...
    def get_workspace(self, workspace_id: str) -> WorkspaceDefinition: ...
    def upsert_workspace(self, workspace: WorkspaceDefinition) -> None: ...
    def delete_workspace(self, workspace_id: str) -> None: ...


class RunRepositoryProtocol(Protocol):
    def save(self, run: RunRecord) -> None: ...
    def save_recovery_transition_if_stale(
        self,
        run: RunRecord,
        *,
        expected_status: str,
        expected_updated_at: str,
        active_lease_after: str,
    ) -> bool: ...
    def get(self, run_id: str) -> RunRecord: ...
    def list_runs(self, *, limit: int = 50, offset: int = 0, status: str = "", workspace_id: str = "") -> list[RunRecord]: ...
    def claim_next_queued(self) -> RunRecord | None: ...
    def delete(self, run_id: str) -> None: ...


class JobStoreProtocol(Protocol):
    def save_job_set(self, run_id: str, set_key: str, jobs: list[JobRecord]) -> None: ...
    def load_job_set(self, run_id: str, set_key: str) -> list[JobRecord]: ...
    def list_job_set_keys(self, run_id: str) -> list[str]: ...
    def load_all_job_sets(self, run_id: str) -> dict[str, list[JobRecord]]: ...
    def load_job_sets_for_runs(self, run_ids: Iterable[str]) -> dict[str, dict[str, list[JobRecord]]]: ...
    def delete_job_set(self, run_id: str, set_key: str) -> None: ...
    def save_blob(self, run_id: str, blob_key: str, payload: Any) -> None: ...
    def load_blob(self, run_id: str, blob_key: str, default: Any = None) -> Any: ...
    def list_blob_keys(self, run_id: str) -> list[str]: ...
    def load_all_blobs(self, run_id: str) -> dict[str, Any]: ...
    def delete_blob(self, run_id: str, blob_key: str) -> None: ...
    def clear_run(self, run_id: str) -> None: ...


class ArtifactStoreProtocol(Protocol):
    def save_artifacts(self, run_id: str, artifacts: list[ArtifactRecord]) -> None: ...
    def load_artifacts(self, run_id: str) -> list[ArtifactRecord]: ...
    def load_artifacts_for_runs(self, run_ids: Iterable[str]) -> dict[str, list[ArtifactRecord]]: ...
    def get_artifact(self, run_id: str, artifact_id: str) -> ArtifactRecord: ...
    def upsert_artifact(self, run_id: str, artifact: ArtifactRecord) -> None: ...
    def delete_artifact(self, run_id: str, artifact_id: str) -> None: ...
    def clear_run(self, run_id: str) -> None: ...


class ReviewStoreProtocol(Protocol):
    def upsert_review(self, review: ReviewRecord) -> None: ...
    def get_review(self, review_id: str) -> ReviewRecord: ...
    def list_reviews(self, *, run_id: str = "", limit: int = 100, offset: int = 0, status: str = "") -> list[ReviewRecord]: ...
    def list_reviews_for_runs(self, run_ids: Iterable[str]) -> dict[str, list[ReviewRecord]]: ...

    def list_tracker_run_ids(self, run_ids: Iterable[str]) -> set[str]: ...
    def append_application_status_history(self, entry: Mapping[str, Any]) -> None: ...
    def list_application_status_history(self, *, user_id: str = "", review_id: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def delete_review(self, review_id: str) -> None: ...


class AuthRepositoryProtocol(Protocol):
    def list_users(self) -> list[UserRecord]: ...
    def get_user(self, user_id: str) -> UserRecord: ...
    def get_user_by_email(self, email: str) -> UserRecord: ...
    def upsert_user(self, user: UserRecord) -> None: ...
    def delete_user(self, user_id: str) -> None: ...
    def list_api_tokens(self, *, user_id: str = "", active_only: bool = False) -> list[ApiTokenRecord]: ...
    def list_api_tokens_for_value(self, token_value: str, *, active_only: bool = False) -> list[ApiTokenRecord]: ...
    def get_api_token(self, token_id: str) -> ApiTokenRecord: ...
    def upsert_api_token(self, token: ApiTokenRecord) -> None: ...
    def delete_api_token(self, token_id: str) -> None: ...
    def create_assisted_apply_connection(self, record: AssistedApplyConnectionRecord) -> None: ...
    def get_assisted_apply_connection(self, request_id: str) -> AssistedApplyConnectionRecord: ...
    def list_assisted_apply_connections(
        self,
        *,
        user_id: str = "",
        status: str = "",
    ) -> list[AssistedApplyConnectionRecord]: ...
    def list_assisted_apply_connections_for_session_prefix(
        self,
        session_token_prefix: str,
    ) -> list[AssistedApplyConnectionRecord]: ...
    def authorize_assisted_apply_connection(
        self,
        request_id: str,
        *,
        user_id: str,
        authorization_code_prefix: str,
        authorization_code_hash: str,
        authorization_code_expires_at: str,
        authorized_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def reject_assisted_apply_connection(
        self,
        request_id: str,
        *,
        user_id: str,
        rejected_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def activate_assisted_apply_connection(
        self,
        request_id: str,
        *,
        extension_origin: str,
        session_token_prefix: str,
        session_token_hash: str,
        session_expires_at: str,
        activated_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def expire_assisted_apply_connection(
        self,
        request_id: str,
        *,
        expected_status: str,
        expired_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def touch_assisted_apply_session(
        self,
        request_id: str,
        *,
        last_used_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def revoke_assisted_apply_connection(
        self,
        request_id: str,
        *,
        user_id: str,
        revoked_at: str,
    ) -> AssistedApplyConnectionRecord | None: ...
    def update_assisted_apply_preferences_metadata(
        self,
        user_id: str,
        *,
        expected_revision: int,
        preferences: AssistedApplyPreferences,
        updated_at: str,
    ) -> bool: ...


class SecretStoreProtocol(Protocol):
    def list_secrets(self, *, workspace_id: str = "", limit: int = 100, offset: int = 0) -> list[SecretRecord]: ...
    def get_secret(self, secret_id: str) -> SecretRecord: ...
    def upsert_secret(self, secret: SecretRecord) -> None: ...
    def delete_secret(self, secret_id: str) -> None: ...


class WorkerStoreProtocol(Protocol):
    def list_workers(self, *, limit: int = 50, offset: int = 0, status: str = "") -> list[WorkerRecord]: ...
    def list_expired_workers(self, *, expires_before: str) -> list[WorkerRecord]: ...
    def get_worker(self, worker_id: str) -> WorkerRecord: ...
    def upsert_worker(self, worker: WorkerRecord) -> None: ...
    def renew_worker_lease_if_owned(
        self,
        observed: WorkerRecord,
        renewed: WorkerRecord,
        *,
        run_attempt_count: int,
    ) -> bool: ...
    def mark_stale_if_expired(
        self,
        worker: WorkerRecord,
        *,
        expires_before: str,
        stale_at: str,
    ) -> bool: ...
    def delete_worker(self, worker_id: str) -> None: ...


class AnalyticsStoreProtocol(Protocol):
    def emit_event(self, event: Mapping[str, Any]) -> None: ...
    def query_rows(self, query: str, parameters: Iterable[Any] = ()) -> list[dict[str, Any]]: ...
    def list_events(self, *, event_name: str = "", user_id: str = "", workspace_id: str = "", run_id: str = "", limit: int = 100, offset: int = 0) -> list[dict[str, Any]]: ...
    def count_events(self, *, event_name: str = "", user_id: str = "", workspace_id: str = "", run_id: str = "") -> int: ...


class ConfigStoreProtocol(Protocol):
    def get_value(self, config_key: str, default: Any = None) -> Any: ...
    def set_value(self, config_key: str, value: Any) -> None: ...
    def delete_value(self, config_key: str) -> None: ...
    def list_values(self, *, prefix: str = "") -> dict[str, Any]: ...


class SourcePolicyStoreProtocol(Protocol):
    def ensure_sites(self, sites: Iterable[Mapping[str, Any]]) -> None: ...
    def set_site_state(self, site_url: str, state: Mapping[str, Any]) -> None: ...
    def mark_workspace_selected(self, *, workspace_id: str, site_urls: Iterable[str]) -> None: ...
    def filter_crawlable_sites(self, sites: Iterable[Mapping[str, Any]], *, workspace_id: str = "") -> list[dict[str, Any]]: ...
    def record_site_yield(self, site_url: str, *, workspace_id: str = "", job_count: int = 0) -> None: ...
    def get_site_policy(self, site_url: str) -> dict[str, Any]: ...
    def get_seen_job_urls(self, *, workspace_id: str = "", source_id: str = "") -> set[str]: ...
    def get_cached_job_postings(self, *, workspace_id: str = "", source_id: str = "") -> list[dict[str, Any]]: ...
    def record_job_url_attempts(self, attempts: Iterable[Mapping[str, Any]]) -> None: ...



class EvidenceStoreProtocol(Protocol):
    def upsert_evidence(self, evidence: EvidenceRecord) -> None: ...
    def get_evidence(self, evidence_id: str) -> EvidenceRecord: ...
    def list_evidence(
        self, *,
        workspace_id: str = "",
        run_id: str = "",
        kind: str = "",
        state: str = "",
        limit: int = 100,
        offset: int = 0,
    ) -> list[EvidenceRecord]: ...
    def append_state_history(self, entry: EvidenceStateHistory) -> None: ...
    def list_state_history(
        self, *,
        evidence_id: str = "",
        limit: int = 100,
    ) -> list[EvidenceStateHistory]: ...
    def delete_evidence(self, evidence_id: str) -> None: ...


class CareerProfileStoreProtocol(Protocol):
    def list_profiles(self, *, user_id: str = "", limit: int = 50, offset: int = 0) -> list[CareerProfile]: ...
    def get_profile(self, profile_id: str) -> CareerProfile: ...
    def upsert_profile(self, profile: CareerProfile) -> None: ...
    def list_profiles_by_workspace(self, workspace_id: str) -> list[CareerProfile]: ...
    def delete_profile(self, profile_id: str) -> None: ...


class AcquisitionStoreProtocol(Protocol):
    def ensure_targets(self, targets: Iterable[Mapping[str, Any]]) -> None: ...
    def list_targets(self, *, include_disabled: bool = True) -> list[dict[str, Any]]: ...
    def get_target(self, target_id: str) -> dict[str, Any]: ...
    def update_target_state(self, target_id: str, *, maturity_state: str, reason: str, zero_yield_streak: int | None = None, attempted_at: str = "", successful_at: str = "") -> None: ...
    def claim_due_cycle(self, *, window_key: str, lease_owner: str, scheduled_at: str, lease_seconds: int = 300, force: bool = False) -> dict[str, Any] | None: ...
    def ensure_cycle_tasks(self, cycle_id: str, targets: Iterable[Mapping[str, Any]]) -> None: ...
    def set_cycle_forecast(self, cycle_id: str, *, requests: int, credits: int) -> None: ...
    def claim_next_task(self, *, cycle_id: str, lease_owner: str, lease_seconds: int = 300) -> dict[str, Any] | None: ...
    def reserve_request(self, **kwargs: Any) -> dict[str, Any]: ...
    def mark_request_dispatching(self, request_id: str) -> None: ...
    def complete_request(self, request_id: str, **kwargs: Any) -> None: ...
    def recover_dispatching_requests(self) -> list[dict[str, Any]]: ...
    def decide_uncertain_request(self, request_id: str, *, decision: str, reason: str = "") -> dict[str, Any]: ...
    def ingest_snapshot(self, **kwargs: Any) -> dict[str, Any]: ...
    def record_attempt(self, **kwargs: Any) -> None: ...
    def complete_task(self, task_id: str, *, status: str, result: Mapping[str, Any], error_code: str = "", error_message: str = "") -> None: ...
    def complete_cycle(self, cycle_id: str, *, status: str, error_code: str = "", error_message: str = "", publication_id: str = "") -> None: ...
    def publish_valid_snapshot(self, *, cycle_id: str, valid_target_ids: Iterable[str], valid_until: str = "") -> str: ...
    def list_cycles(self, *, limit: int = 50, offset: int = 0) -> list[dict[str, Any]]: ...
    def get_cycle(self, cycle_id: str) -> dict[str, Any]: ...
    def list_cycle_targets(self, cycle_id: str) -> list[dict[str, Any]]: ...
    def get_cycle_report(self, cycle_id: str) -> dict[str, Any]: ...
    def get_quality_metrics(self, cycle_id: str = "") -> dict[str, Any]: ...
    def get_latest_report(self) -> dict[str, Any] | None: ...
    def get_public_catalog(self, *, limit: int = 50, offset: int = 0) -> dict[str, Any]: ...
    def record_job_rejections(
        self,
        *,
        request_id: str,
        cycle_id: str,
        task_id: str,
        target_id: str,
        rejections: Iterable[Mapping[str, Any]],
        observed_at: str = "",
    ) -> None: ...
    def publish_staging_snapshot(
        self,
        *,
        cycle_id: str,
        valid_target_ids: Iterable[str],
        valid_until: str = "",
    ) -> str: ...
    def get_staging_catalog(
        self,
        *,
        publication_id: str = "",
        limit: int = 50,
        offset: int = 0,
    ) -> dict[str, Any]: ...
    def promote_staging_publication(self, publication_id: str) -> str: ...
    def get_target_history(self, target_id: str) -> dict[str, Any]: ...
    def get_cycle_source_metrics(self, cycle_id: str) -> list[dict[str, Any]]: ...
    def list_admin_job_inspections(self, *, search: str = "", limit: int = 100, offset: int = 0) -> dict[str, Any]: ...
    def get_admin_job_inspection(self, canonical_job_id: str) -> dict[str, Any] | None: ...
    def resolve_admin_job_apply_url(self, canonical_job_id: str, *, actor_user_id: str = "") -> dict[str, Any]: ...


class PersonalizedJobsStoreProtocol(Protocol):
    """User-scoped state plus read-only access to the shared publication head."""

    def get_preferences(self, user_id: str) -> dict[str, Any] | None: ...
    def upsert_preferences(self, user_id: str, payload: Mapping[str, Any], *, profile_id: str = "", expected_revision: int | None = None) -> dict[str, Any]: ...
    def get_default_saved_search(self, user_id: str) -> dict[str, Any] | None: ...
    def upsert_default_saved_search(self, user_id: str, payload: Mapping[str, Any], *, name: str = "Default search") -> dict[str, Any]: ...
    def list_dispositions(self, user_id: str, *, states: Iterable[str] = ()) -> dict[str, dict[str, Any]]: ...
    def set_disposition(self, user_id: str, canonical_job_id: str, *, state: str, source_of_change: str = "user", reason_code: str = "") -> dict[str, Any]: ...
    def record_event(self, user_id: str, *, event_name: str, canonical_job_id: str = "", reason_code: str = "", payload: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
    def get_evaluation(self, user_id: str, canonical_job_id: str, *, job_version_id: str = "", preferences_revision: int = 0, evaluator_version: str = "phase_c_v1") -> dict[str, Any] | None: ...
    def save_evaluation(self, user_id: str, canonical_job_id: str, *, job_version_id: str, preferences_revision: int, evaluator_version: str, state: str, payload: Mapping[str, Any]) -> None: ...
    def get_description_intelligence(self, version_id: str, *, content_hash: str = "") -> dict[str, Any] | None: ...
    def save_description_intelligence(self, *, version_id: str, canonical_job_id: str, content_hash: str, summary: Mapping[str, Any], structured_description: Mapping[str, Any], original_posting: Mapping[str, Any], provider: str, model: str = "", prompt_version: str = "", generated_at: str = "") -> dict[str, Any]: ...
    def get_intelligence_cache(self, key: Mapping[str, Any]) -> dict[str, Any] | None: ...
    def enqueue_intelligence(self, key: Mapping[str, Any]) -> dict[str, Any]: ...
    def claim_next_intelligence(self) -> dict[str, Any] | None: ...
    def complete_intelligence(self, cache_id: str, *, state: str, payload: Mapping[str, Any], error: str = "") -> None: ...
    def list_published_job_rows(self) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]: ...
    def get_current_publication(self) -> dict[str, Any] | None: ...
    def query_published_jobs(
        self,
        user_id: str,
        *,
        filters: Mapping[str, Any] | None = None,
        limit: int = 25,
        cursor: Mapping[str, Any] | None = None,
        include_hidden: bool = False,
        hidden_only: bool = False,
    ) -> dict[str, Any]: ...
    def get_published_company_page(self, company_id: str, user_id: str, *, limit: int = 25) -> dict[str, Any]: ...
    def list_hidden_published_jobs(self, user_id: str, *, limit: int = 25, cursor: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
    def list_dispositions_for_jobs(self, user_id: str, canonical_job_ids: Iterable[str]) -> dict[str, dict[str, Any]]: ...
    def list_cached_descriptions(self, version_ids: Iterable[str]) -> dict[str, dict[str, Any]]: ...
    def list_intelligence_cache_entries(self, canonical_job_ids: Iterable[str], *, user_id: str = "", intelligence_kind: str = "") -> list[dict[str, Any]]: ...
    def list_evaluations_for_jobs(self, user_id: str, canonical_job_ids: Iterable[str], *, preferences_revision: int = 0, evaluator_version: str = "phase_e_v2") -> dict[str, dict[str, Any]]: ...
    def get_published_filter_capabilities(self) -> dict[str, bool]: ...
    def get_published_job_row(self, canonical_job_id: str) -> dict[str, Any] | None: ...
    def get_published_company_rows(self, company_id: str) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]: ...
    def get_company_profile(self, company_id: str) -> dict[str, Any] | None: ...
    def upsert_company_profile(self, company_id: str, profile: Mapping[str, Any], *, logo_object_key: str = "", logo_source_url: str = "", logo_content_hash: str = "", logo_content_type: str = "", logo_verified_at: str = "") -> dict[str, Any]: ...
    def list_company_enrichment_targets(self, *, now: str, limit: int = 25) -> list[dict[str, Any]]: ...
    def claim_company_enrichment_target(self, company_id: str, *, cycle_key: str, lease_owner: str, lease_expires_at: str, now: str) -> dict[str, Any] | None: ...
    def finish_company_enrichment_attempt(self, attempt_id: str, *, status: str, request_count: int, cost_units: float, fields_available: int, fields_written: int, logo_cached: bool, yield_payload: Mapping[str, Any] | None = None, error_code: str = "", error_message: str = "", next_attempt_at: str = "", now: str) -> dict[str, Any]: ...
    def list_company_enrichment_attempts(self, *, company_id: str = "", limit: int = 100) -> list[dict[str, Any]]: ...



@dataclass(slots=True)
class BackendRepositories:
    workspace_repository: WorkspaceRepositoryProtocol
    run_repository: RunRepositoryProtocol
    job_store: JobStoreProtocol
    artifact_store: ArtifactStoreProtocol
    review_store: ReviewStoreProtocol
    auth_repository: AuthRepositoryProtocol
    secret_store: SecretStoreProtocol
    worker_store: WorkerStoreProtocol
    analytics_store: AnalyticsStoreProtocol
    config_store: ConfigStoreProtocol
    source_policy_store: SourcePolicyStoreProtocol | None = None
    career_profile_store: CareerProfileStoreProtocol | None = None
    career_profile_store: CareerProfileStoreProtocol | None = None
    evidence_store: EvidenceStoreProtocol | None = None
    acquisition_store: AcquisitionStoreProtocol | None = None
    personalized_jobs_store: PersonalizedJobsStoreProtocol | None = None

