"""Provider-neutral, inactive-by-default enrichment foundation."""

from .contracts import (
    EnrichmentCandidate,
    EnrichmentProvider,
    EnrichmentRequest,
    EvidenceEnvelope,
    LicenceMetadata,
    ProviderBudget,
    ProviderCapability,
    ProviderExecutionContext,
    ProviderMetadata,
    ProviderResult,
    ProviderResultState,
    RetentionPolicy,
    VERSION_KINDS,
)
from .evaluation import (
    ALTERNATE_RULE_VERSION,
    AdjudicationMetadata,
    DEFAULT_RULE_VERSION,
    GoldenLabel,
    OfflineTrialOrchestrator,
    ReplayComparison,
    TrialConfig,
    TrialOutput,
    TrialRun,
    compare_replays,
    render_markdown_report,
    report_json,
)

__all__ = [
    "EnrichmentCandidate",
    "EnrichmentProvider",
    "EnrichmentRequest",
    "EvidenceEnvelope",
    "LicenceMetadata",
    "ProviderBudget",
    "ProviderCapability",
    "ProviderExecutionContext",
    "ProviderMetadata",
    "ProviderResult",
    "ProviderResultState",
    "RetentionPolicy",
    "VERSION_KINDS",
    "ALTERNATE_RULE_VERSION",
    "AdjudicationMetadata",
    "DEFAULT_RULE_VERSION",
    "GoldenLabel",
    "OfflineTrialOrchestrator",
    "ReplayComparison",
    "TrialConfig",
    "TrialOutput",
    "TrialRun",
    "compare_replays",
    "render_markdown_report",
    "report_json",
]
