from __future__ import annotations

from backend.domain.models import (
    JobSource,
    ProfileRef,
    PromptSetRef,
    StageDefinition,
    WorkflowTemplate,
    WorkspaceDefinition,
)


DEFAULT_WORKFLOW_TEMPLATES = [
    WorkflowTemplate(
        id="white_collar_linkedin_v1",
        name="White-Collar LinkedIn",
        description="LinkedIn discovery, enrichment, filtering, ranking, and tailored CV generation.",
        stages=[
            StageDefinition(
                stage_id="linkedin_acquire",
                stage_type="legacy.linkedin.acquire",
                name="Acquire LinkedIn Jobs",
                output_key="linkedin_stage1_jobs",
                config={"connector_id": "linkedin_search"},
            ),
            StageDefinition(
                stage_id="white_collar_stage2_filter",
                stage_type="legacy.white_collar.local_filter",
                name="Local Filter",
                input_keys=["linkedin_stage1_jobs"],
                output_key="white_collar_stage2_jobs",
            ),
            StageDefinition(
                stage_id="white_collar_stage3_rank",
                stage_type="legacy.white_collar.rank",
                name="Rank and Final Filter",
                input_keys=["white_collar_stage2_jobs"],
                output_key="production_jobs",
            ),
            StageDefinition(
                stage_id="white_collar_docs",
                stage_type="legacy.white_collar.docs",
                name="Generate CV and Export",
                input_keys=["production_jobs"],
                output_key="generated_jobs",
                config={
                    "generation_id": "white_collar_cv_generation",
                    "renderer_id": "docx_pdf_renderer",
                },
            ),
        ],
        default_run_settings={"mode": "linkedin"},
    ),
    WorkflowTemplate(
        id="white_collar_manual_urls_v1",
        name="White-Collar Manual URLs",
        description="Manual URL ingestion, normalization, dedupe, and tailored CV generation.",
        stages=[
            StageDefinition(
                stage_id="manual_url_ingest",
                stage_type="legacy.manual_url.ingest",
                name="Ingest Manual URLs",
                output_key="manual_jobs",
                config={"connector_id": "manual_url"},
            ),
            StageDefinition(
                stage_id="manual_dedupe",
                stage_type="legacy.jobs.merge",
                name="Deduplicate Manual Jobs",
                input_keys=["manual_jobs"],
                output_key="production_jobs",
                config={"dedupe_against_tracker": True},
            ),
            StageDefinition(
                stage_id="white_collar_docs",
                stage_type="legacy.white_collar.docs",
                name="Generate CV and Export",
                input_keys=["production_jobs"],
                output_key="generated_jobs",
                config={
                    "generation_id": "white_collar_cv_generation",
                    "renderer_id": "docx_pdf_renderer",
                },
            ),
        ],
        default_run_settings={"mode": "manual_urls"},
    ),
    WorkflowTemplate(
        id="white_collar_combined_v1",
        name="White-Collar Combined",
        description="LinkedIn discovery plus manual URL ingestion merged into one production stage.",
        stages=[
            StageDefinition(
                stage_id="linkedin_acquire",
                stage_type="legacy.linkedin.acquire",
                name="Acquire LinkedIn Jobs",
                output_key="linkedin_stage1_jobs",
                config={"connector_id": "linkedin_search"},
            ),
            StageDefinition(
                stage_id="white_collar_stage2_filter",
                stage_type="legacy.white_collar.local_filter",
                name="Local Filter",
                input_keys=["linkedin_stage1_jobs"],
                output_key="white_collar_stage2_jobs",
            ),
            StageDefinition(
                stage_id="white_collar_stage3_rank",
                stage_type="legacy.white_collar.rank",
                name="Rank and Final Filter",
                input_keys=["white_collar_stage2_jobs"],
                output_key="linkedin_accepted_jobs",
            ),
            StageDefinition(
                stage_id="manual_url_ingest",
                stage_type="legacy.manual_url.ingest",
                name="Ingest Manual URLs",
                output_key="manual_jobs",
                config={"connector_id": "manual_url"},
            ),
            StageDefinition(
                stage_id="merge_sources",
                stage_type="legacy.jobs.merge",
                name="Merge Accepted Jobs",
                input_keys=["linkedin_accepted_jobs", "manual_jobs"],
                output_key="production_jobs",
                config={"dedupe_against_tracker": True},
            ),
            StageDefinition(
                stage_id="white_collar_docs",
                stage_type="legacy.white_collar.docs",
                name="Generate CV and Export",
                input_keys=["production_jobs"],
                output_key="generated_jobs",
                config={
                    "generation_id": "white_collar_cv_generation",
                    "renderer_id": "docx_pdf_renderer",
                },
            ),
        ],
        default_run_settings={"mode": "combined"},
    ),
    WorkflowTemplate(
        id="blue_collar_default_v1",
        name="Blue-Collar Default",
        description="Blue-collar portal scraping, filtering, classification, role CV generation, and packaging.",
        stages=[
            StageDefinition(
                stage_id="blue_stage1",
                stage_type="legacy.blue_collar.stage1",
                name="Scrape Blue-Collar Sources",
                output_key="blue_stage1_jobs",
                config={"connector_id": "blue_collar_portals"},
            ),
            StageDefinition(
                stage_id="blue_stage2",
                stage_type="legacy.blue_collar.stage2",
                name="Blue-Collar Filter",
                input_keys=["blue_stage1_jobs"],
                output_key="blue_stage2_jobs",
            ),
            StageDefinition(
                stage_id="blue_stage3",
                stage_type="legacy.blue_collar.stage3",
                name="Blue-Collar Classifier",
                input_keys=["blue_stage2_jobs"],
                output_key="blue_stage3_jobs",
            ),
            StageDefinition(
                stage_id="blue_stage4",
                stage_type="legacy.blue_collar.stage4",
                name="Blue-Collar Role CV Builder",
                input_keys=["blue_stage3_jobs"],
                output_key="blue_stage4_role_cvs",
                config={"generation_id": "blue_collar_role_cv_generation"},
            ),
            StageDefinition(
                stage_id="blue_stage5",
                stage_type="legacy.blue_collar.stage5",
                name="Blue-Collar Packaging",
                input_keys=["blue_stage3_jobs", "blue_stage4_role_cvs"],
                output_key="blue_stage5_packages",
                config={"renderer_id": "blue_collar_package_renderer"},
            ),
        ],
        default_run_settings={"mode": "blue_collar"},
    ),
]


DEFAULT_WORKSPACES = [
    WorkspaceDefinition(
        id="white_collar_linkedin",
        name="White-Collar LinkedIn Workspace",
        workflow_template_id="white_collar_linkedin_v1",
        description="Default workspace for LinkedIn-driven white-collar job discovery.",
        workspace_type="white_collar",
        settings={"config_loader": "job_seeker"},
        feature_flags={
            "enable_linkedin_search": True,
            "enable_manual_urls": False,
            "enable_blue_collar_sources": False,
        },
        profiles=[ProfileRef(id="white_collar_default", label="Default white-collar CV profile")],
        prompt_sets=[PromptSetRef(id="white_collar_default", family="white_collar")],
        sources=[JobSource(id="linkedin_primary", connector_id="linkedin_search")],
        metadata={"preset": "linkedin"},
    ),
    WorkspaceDefinition(
        id="white_collar_manual_urls",
        name="White-Collar Manual URL Workspace",
        workflow_template_id="white_collar_manual_urls_v1",
        description="Default workspace for manually curated white-collar job URLs.",
        workspace_type="white_collar",
        settings={"config_loader": "job_seeker", "skip_filtering_for_manual_urls": True},
        feature_flags={
            "enable_linkedin_search": False,
            "enable_manual_urls": True,
            "enable_blue_collar_sources": False,
        },
        profiles=[ProfileRef(id="white_collar_default", label="Default white-collar CV profile")],
        prompt_sets=[PromptSetRef(id="white_collar_default", family="white_collar")],
        sources=[JobSource(id="manual_curated_urls", connector_id="manual_url")],
        metadata={"preset": "manual_urls"},
    ),
    WorkspaceDefinition(
        id="white_collar_combined",
        name="White-Collar Combined Workspace",
        workflow_template_id="white_collar_combined_v1",
        description="Default workspace for LinkedIn discovery plus manual URL supplementation.",
        workspace_type="white_collar",
        settings={"config_loader": "job_seeker"},
        feature_flags={
            "enable_linkedin_search": True,
            "enable_manual_urls": True,
            "enable_blue_collar_sources": False,
        },
        profiles=[ProfileRef(id="white_collar_default", label="Default white-collar CV profile")],
        prompt_sets=[PromptSetRef(id="white_collar_default", family="white_collar")],
        sources=[
            JobSource(id="linkedin_primary", connector_id="linkedin_search"),
            JobSource(id="manual_curated_urls", connector_id="manual_url"),
        ],
        metadata={"preset": "combined"},
    ),
    WorkspaceDefinition(
        id="blue_collar_default",
        name="Blue-Collar Workspace",
        workflow_template_id="blue_collar_default_v1",
        description="Default workspace for blue-collar acquisition and packaging flows.",
        workspace_type="blue_collar",
        settings={"config_loader": "blue_collar"},
        feature_flags={
            "enable_linkedin_search": False,
            "enable_manual_urls": False,
            "enable_blue_collar_sources": True,
        },
        profiles=[ProfileRef(id="blue_collar_baseline", label="Baseline blue-collar CV profile")],
        prompt_sets=[PromptSetRef(id="blue_collar_default", family="blue_collar")],
        sources=[JobSource(id="blue_collar_multi_portal", connector_id="blue_collar_portals")],
        metadata={"preset": "blue_collar"},
    ),
]
